---
title: "shinypipe vignette"
author: "Karthik Rajendran"
date: "December, 2017"
output: 
  html_document:
    toc : true
    toc_float : true
    code_folding: hide
runtime: shiny
---

```{r Library, include=F}
rm(list = ls())
library(datasets)
library(data.table)
library(ggplot2)

runWithoutInstall <- T
ifelse(runWithoutInstall,
       sapply(list.files(path = "../R/", pattern="*R", full.names = T), source),
       library(shinypipe))

t.data <- fread("./boston.csv", header = T)
TEST_PCT <- 10
VAL_PCT <- 40
```

### Data
```{r}
renderDataTable(t.data)
```

### Linear Regression
Perform a simple regression using the formula

```{r}
renderPrint(summary(lm(MEDV ~ ., t.data)))
```

```{r}

```{r}
library(shinyFiles)
shinyFilesExample()
```

```

<!-- ### Using params: example 1 -->

<!-- Fit a generalized linear model -->

<!-- ```{r} -->
<!-- ui.params("params", -->
<!--           family  = list("", c("gaussian", "poisson"))) -->
<!-- r.glmParams <- callModule(s.params, "params") -->

<!-- renderPrint({ -->
<!--   f <- do.call(stats::glm, c(list(formula = r.fml(), data = r.data()), r.glmParams())) -->
<!--   f$coefficients -->
<!-- }) -->

<!-- ``` -->

<!-- ### Using params: example 2 -->

<!-- ```{r} -->
<!-- ui.params("paramList", -->
<!--           name  = list("", NA, placeholder = "Enter your name here", width = '100%'), -->
<!--           dob   = list(Sys.Date(), NA, label = "Date of birth")) -->
<!-- r.paramList <- callModule(s.params, "paramList") -->

<!-- my.f <- function(name, dob) { -->
<!--   age <- (Sys.Date() - dob) -->
<!--   if (is.null(name) || name == "") return ("Enter your name above."); -->
<!--   if (age <= 0) return ("Enter a valid date"); -->
<!--   return (paste0("You're ", age, " day(s) old, ", name, ".")) -->
<!-- }  -->

<!-- renderPrint(do.call(my.f, r.paramList())) -->
<!-- ``` -->



